version: "3.6"
services:
  strapi:
    build:
      context: ./
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
    networks:
      - strapi

  nextjs:
    container_name: nextjs
    build:
      context: ./nextjs-client
    command: /bin/bash -c "./wait-for-it.sh strapi:1337 -- yarn build && yarn start"
    restart: unless-stopped
    env_file: ./nextjs-client/.env
    environment:
      - CMS_HOST=strapi:1337
    links:
      - strapi
    depends_on:
      - strapi
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge
