name: basic

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install SSH Key
      # You may pin to the exact commit or the version.
      # uses: shimataro/ssh-key-action@3c9b0fc6f2d223b8450b02a0445f526350fc73e0
      uses: shimataro/ssh-key-action@v2.3.1
      with:
        # SSH private key
        key: ${{ secrets.SSH_SECRET_KEY }}
        # SSH key file name (default: id_rsa)
        name: id_rsa
        # public keys of SSH servers
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    - run: ssh alodi@developer.alodi.app -vvv
